version: '3.1'
services:
  tensorflow:
    container_name: f743-pythonic
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: sleep 10000000
    volumes:
      - ./outputs:/tf/outputs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]