version: '3.1'
services:
  tensorflow:
    container_name: tf743-jupyter
    build:
      context: .
      dockerfile: Dockerfile-Jupyter
    restart: unless-stopped
    command: jupyter notebook --ip=0.0.0.0 --allow-root --NotebookApp.token='' --NotebookApp.password=''
    volumes:
      - ./notebooks:/tf/notebooks
      - ./data:/tf/data
      - ./snapshots:/tf/snapshots
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    ports:
      - '8888:8888'