FROM tensorflow/tensorflow:latest-gpu-jupyter
WORKDIR /tf
# Install dependencies
COPY . .
RUN pip install --upgrade pip setuptools wheel
RUN pip install --upgrade -r requirements.txt

# Copy source code

EXPOSE 8888

# Run the application
CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--allow-root", "--no-browser", "--NotebookApp.password=''"]

